# Generated by Django 5.0.4 on 2025-08-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganado',
            name='LitroLeche',
            field=models.CharField(db_column='LitrosLeche', default=0, max_length=2),
        ),
    ]
