# Generated by Django 5.0.4 on 2025-08-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaRazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tablarazas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
            ],
            options={
                'db_table': 'tablavacunas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', default='Parcela Genérica', max_length=100)),
                ('estado', models.CharField(db_column='Estado', default='Activo', max_length=9)),
            ],
            options={
                'db_table': 'tipoparcela',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocria', models.CharField(db_column='CodigoCria', max_length=12)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='Ganado/')),
                ('crias', models.CharField(db_column='Crias', max_length=2)),
                ('codigoscrias', models.TextField(db_column='CodigosCrias')),
                ('codigopapa', models.CharField(db_column='CodigoPapa', max_length=12)),
                ('codigomama', models.CharField(db_column='CodigoMama', max_length=12)),
                ('edad', models.CharField(db_column='Edad', max_length=2)),
                ('infovacunas', models.TextField(db_column='InfoVacunas')),
                ('enfermedades', models.TextField(db_column='Enfermedades')),
                ('estado', models.CharField(db_column='Estado', max_length=7)),
                ('razas', models.CharField(db_column='Razas', max_length=255)),
                ('idparcela', models.ForeignKey(db_column='IdParcela', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipoparcela')),
            ],
            options={
                'db_table': 'ganado',
                'managed': True,
            },
        ),
    ]
