# Generated by Django 5.1.6 on 2025-09-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'cultivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaRazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tablarazas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
            ],
            options={
                'db_table': 'tablavacunas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_cultivo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', default='Parcela Genérica', max_length=100)),
                ('estado', models.CharField(db_column='Estado', default='Activo', max_length=9)),
            ],
            options={
                'db_table': 'tipoparcela',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fertilizante', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('QUIMICO', 'Químico'), ('ORGANICO', 'Orgánico'), ('OTRO', 'Otro')], default='QUIMICO', max_length=10)),
                ('dosis', models.CharField(default='N/A', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='AppInventario.cultivo')),
            ],
            options={
                'db_table': 'fertilizacion',
            },
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.CASCADE, to='AppInventario.tipocultivo'),
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocria', models.CharField(db_column='CodigoCria', max_length=12)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='Ganado/')),
                ('crias', models.CharField(db_column='Crias', max_length=2)),
                ('codigoscrias', models.TextField(db_column='CodigosCrias')),
                ('codigopapa', models.CharField(db_column='CodigoPapa', max_length=12)),
                ('codigomama', models.CharField(db_column='CodigoMama', max_length=12)),
                ('edad', models.CharField(db_column='Edad', max_length=2)),
                ('infovacunas', models.TextField(db_column='InfoVacunas')),
                ('enfermedades', models.TextField(db_column='Enfermedades')),
                ('estado', models.CharField(db_column='Estado', max_length=7)),
                ('razas', models.CharField(db_column='Razas', max_length=255)),
                ('idparcela', models.ForeignKey(db_column='IdParcela', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='AppInventario.tipoparcela')),
            ],
            options={
                'db_table': 'ganado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='UserName', max_length=100)),
                ('nombres', models.CharField(db_column='Nombres', max_length=120)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=70)),
                ('correo', models.CharField(db_column='Correo', max_length=255)),
                ('numerodocumento', models.CharField(db_column='NumeroDocumento', max_length=12)),
                ('rol', models.CharField(db_column='Rol', max_length=7)),
                ('clave', models.CharField(db_column='Clave', max_length=100)),
                ('estado', models.CharField(db_column='Estado', max_length=9)),
                ('idtipodocumento', models.ForeignKey(db_column='IdTipoDocumento', on_delete=django.db.models.deletion.DO_NOTHING, to='AppInventario.tipodocumentos')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
