# Generated by Django 5.1.6 on 2025-09-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanadoInactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocria', models.CharField(db_column='CodigoCria', max_length=12)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='Ganado/')),
                ('crias', models.CharField(db_column='Crias', max_length=2)),
                ('codigoscrias', models.TextField(db_column='CodigosCrias')),
                ('codigopapa', models.CharField(db_column='CodigoPapa', max_length=12)),
                ('codigomama', models.CharField(db_column='CodigoMama', max_length=12)),
                ('edad', models.CharField(db_column='Edad', max_length=2)),
                ('infovacunas', models.TextField(db_column='InfoVacunas')),
                ('enfermedades', models.TextField(db_column='Enfermedades')),
                ('estado', models.CharField(db_column='Estado', max_length=7)),
                ('razas', models.CharField(db_column='Razas', max_length=255)),
                ('idparcela', models.ForeignKey(db_column='IdParcela', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='AppInventario.tipoparcela')),
            ],
            options={
                'db_table': 'GanadoInactivo',
                'managed': True,
            },
        ),
    ]
