# Generated by Django 5.1.6 on 2025-09-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0003_alter_enfermedades_options_alter_ganado_options_and_more'),
    ]

    operations = [
    ]
