# Generated by Django 5.1.6 on 2025-09-23 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0003_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.usuarios'),
        ),
        migrations.AlterModelTable(
            name='codigo',
            table='codigo_recuperacion',
        ),
    ]
