# Generated by Django 5.1.6 on 2025-09-23 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_codigo_created_at_alter_codigo_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='user',
        ),
        migrations.AddField(
            model_name='codigo',
            name='user_id',
            field=models.IntegerField(default=0, help_text='ID del usuario en la tabla usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
