# Generated by Django 5.1.6 on 2025-08-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0002_cultivo_tipocultivo_fertilizacion_cultivo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ganado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablarazas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablavacunas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipodocumentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoparcela',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
