# Generated by Django 5.1.6 on 2025-08-05 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0003_tablavacunas_remove_cultivo_tipo_cultivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizacion',
            name='dosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fertilizacion',
            name='tipo',
            field=models.CharField(choices=[('QUIMICO', 'Fertilizante químico'), ('ORGANICO', 'Abono orgánico'), ('OTRO', 'Otro tipo')], default='QUIMICO', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificacionCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('cosecha', 'Cosecha próxima'), ('sin_fertilizar', 'Sin fertilizar'), ('re_fertilizar', 'Volver a fertilizar')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.cultivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.usuarios')),
            ],
        ),
    ]
