# Generated by Django 5.1.6 on 2025-08-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_fertilizacion_dosis_fertilizacion_tipo_and_more'),
    ]

    operations = [
    ]
