# Generated by Django 5.1.6 on 2025-08-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'cultivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_cultivo',
            },
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fertilizante', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='AppInventario.cultivo')),
            ],
            options={
                'db_table': 'fertilizacion',
            },
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.CASCADE, to='AppInventario.tipocultivo'),
        ),
    ]
